title: Kokua-Hawai'i
description: An application dedicated to presenting COVID-19 resources in an easily accessible, understandable interface for optimum user experience.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions